language: python

python:
  - 2.7
  - 3.5
  - 3.6

env:
  global:
    - TEST_DIR=/tmp/_approxposterior/
    - PIP_DEPS="numpy matplotlib scipy george emcee corner sklearn pytest

before_install:
  - pip install pip --upgrade
  - pip install $PIP_DEPS

install:
  - python setup.py install

script:
  - mkdir -p $TEST_DIR
  - cd $TEST_DIR && python -m pytest --pyargs pdvega --doctest-modules
