language: python

python:
  - 3.5
  - 3.6
  - 3.7

env:
  global:
    - TEST_DIR=/tmp/_approxposterior/

cache: pip

addons:
  apt:
    packages:
    - libeigen3-dev

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda2/bin:$PATH
  - conda update --yes conda
  - pip install pip --upgrade

install:
  - conda create --yes -n test python=$TRAVIS_PYTHON_VERSION
  - source activate test
  - conda install -c conda-forge --yes numpy scipy scikit-learn corner pytest pybind11 george h5py pyDOE emcee
  - python setup.py install

script:
  - mkdir -p $TEST_DIR
  - cd $TEST_DIR && python -m pytest --pyargs approxposterior --doctest-modules
